server:
  port: 8080
spring:
#  datasource:
#    url: "jdbc:h2:mem:testdb"
#    username: "test"

  liquibase:
    change-log: "liquibase/master.xml"
    url: jdbc:h2:mem:gateway;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    user: test
    password:
    enabled: true

  r2dbc:
    url: r2dbc:h2:mem:///gateway;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: test
    password:
